SELECT id,
       title,
       slug,
       description,
       category,
       "venueId",
       capacity,
       "bookedCount",
       price,
       currency,
       "startDate",
       "endDate",
       status,
       "imageUrl",
       "videoUrl",
       "organizerId",
       "createdAt",
       "updatedAt",
       "publishedAt"
FROM public.events
LIMIT 1000;